export const products = {
  men: {
    "nike-react-infinity-run-flyknit": {
      id: 1,
      name: "Nike React Infinity Run Flyknit",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 160,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg",
      slug: "nike-react-infinity-run-flyknit",
      featured: 0,
    },
    "nike-react-miler": {
      id: 2,
      name: "Nike React Miler",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 130,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg",
      slug: "nike-react-miler",
      featured: 1,
    },
    "nike-air-zoom-pegasus-37": {
      id: 3,
      name: "Nike Air Zoom Pegasus 37",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-33b0a0a5-c171-46cc-ad20-04a768703e47/air-zoom-pegasus-37-womens-running-shoe-Jl0bDf.jpg",
      slug: "nike-air-zoom-pegasus-37",
      featured: 0,
    },
    "nike-joyride-run-flyknit": {
      id: 4,
      name: "Nike Joyride Run Flyknit",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 180,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/99a7d3cb-e40c-4474-91c2-0f2e6d231fd2/joyride-run-flyknit-womens-running-shoe-HcfnJd.jpg",
      slug: "nike-joyride-run-flyknit",
      featured: 0,
    },
    "nike-mercurial-vapor-13-elite-fg": {
      id: 5,
      name: "Nike Mercurial Vapor 13 Elite FG",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 250,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9dda6202-e2ff-4711-9a09-0fcb7d90c164/mercurial-vapor-13-elite-fg-firm-ground-soccer-cleat-14MsF2.jpg",
      slug: "nike-mercurial-vapor-13-elite-fg",
      featured: 0,
    },
    "nike-phantom-vision-elite-dynamic": {
      id: 6,
      name: "Nike Phantom Vision Elite",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 140,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/s1amp7uosrn0nqpsxeue/phantom-vision-elite-dynamic-fit-fg-firm-ground-soccer-cleat-19Kv1V.jpg",
      slug: "nike-phantom-vision-elite-dynamic-fit-fg",
      featured: 0,
    },
    "nike-phantom-venom-academy-fg": {
      id: 7,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 210,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom": {
      id: 8,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 250,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom-fg": {
      id: 9,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 230,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/021/545/501/original/507173_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom-academy": {
      id: 10,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/019/994/877/original/AJ7747_800.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom-academy-f": {
      id: 11,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 150,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/750/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-vox-elite-fg": {
      id: 12,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 210,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/021/321/832/original/503571_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nike: {
      id: 13,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 180,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/750/attachments/product_template_pictures/images/021/562/245/original/480142_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nikeee: {
      id: 14,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 119,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/011/292/904/original/298048_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nik: {
      id: 15,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 179,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/attachments/product_template_pictures/images/020/249/043/original/494127_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nikee: {
      id: 16,
      name: "Nike Phantom Venom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 220,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/attachments/product_template_pictures/images/010/988/952/original/180155_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
  },
  women: {},

  kids: {},

  customize: {},
};

export default products;
