export const products = {
  men: {
    "nike-react-infinity-run-flyknit": {
      id: 1,
      name: "Nike React Infinity Run Flyknit",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 160,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg",
      slug: "nike-react-infinity-run-flyknit",
      featured: 0,
    },
    "nike-react-miler": {
      id: 2,
      name: "Nike React Miler",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 130,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg",
      slug: "nike-react-miler",
      featured: 1,
    },
    "nike-air-zoom-pegasus-37": {
      id: 3,
      name: "Nike Air Zoom Pegasus",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-33b0a0a5-c171-46cc-ad20-04a768703e47/air-zoom-pegasus-37-womens-running-shoe-Jl0bDf.jpg",
      slug: "nike-air-zoom-pegasus-37",
      featured: 0,
    },
    "nike-joyride-run-flyknit": {
      id: 4,
      name: "Nike Joyride Run Flyknit",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      price: 180,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/99a7d3cb-e40c-4474-91c2-0f2e6d231fd2/joyride-run-flyknit-womens-running-shoe-HcfnJd.jpg",
      slug: "nike-joyride-run-flyknit",
      featured: 0,
    },
    "nike-mercurial-vapor-13-elite-fg": {
      id: 5,
      name: "Nike Mercurial Vapor Elite",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 250,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9dda6202-e2ff-4711-9a09-0fcb7d90c164/mercurial-vapor-13-elite-fg-firm-ground-soccer-cleat-14MsF2.jpg",
      slug: "nike-mercurial-vapor-13-elite-fg",
      featured: 0,
    },
    "nike-phantom-vision-elite-dynamic": {
      id: 6,
      name: "Nike Phantom Vision Elite",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 140,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/s1amp7uosrn0nqpsxeue/phantom-vision-elite-dynamic-fit-fg-firm-ground-soccer-cleat-19Kv1V.jpg",
      slug: "nike-phantom-vision-elite-dynamic-fit-fg",
      featured: 0,
    },
    "nike-phantom-venom-academy-fg": {
      id: 7,
      name: "Nike Phantom Venom",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 210,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom": {
      id: 8,
      name: "Nike Phantom Academy",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 250,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom-fg": {
      id: 9,
      name: "Nike Phantom FG",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 230,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/021/545/501/original/507173_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom-academy": {
      id: 10,
      name: "Nike Air Force ",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/019/994/877/original/AJ7747_800.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-venom-academy-f": {
      id: 11,
      name: "Nike Air JF",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 150,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/750/attachments/product_template_pictures/images/011/119/994/original/218099_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    "nike-phantom-vox-elite-fg": {
      id: 12,
      name: "Nike Jelly Run",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 210,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/021/321/832/original/503571_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nike: {
      id: 13,
      name: "Nike Phantom France",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 180,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/750/attachments/product_template_pictures/images/021/562/245/original/480142_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nikeee: {
      id: 14,
      name: "Addidas Line Run",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 119,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/375/attachments/product_template_pictures/images/011/292/904/original/298048_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nik: {
      id: 15,
      name: "Nike Air Capsule",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 179,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/attachments/product_template_pictures/images/020/249/043/original/494127_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
    nikee: {
      id: 16,
      name: "Nike Phantom France Light",
      brand: "NIKE",
      gender: "MEN",
      category: "FOOTBALL",
      price: 220,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://image.goat.com/attachments/product_template_pictures/images/010/988/952/original/180155_00.png.png",
      slug: "nike-phantom-venom-academy-fg",
      featured: 0,
    },
  },
  women: {
    "Nike Air Max ExceeNike Air Max Excee": {
      id: 1,
      name: "Nike Air Max Excee",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6bed1e64-09ed-4f2d-90c7-6d5e0f197ff9/air-max-excee-womens-shoes-jKsgMj.png",
    },
    "Nike Air Max 90 Futura": {
      id: 2,
      name: "Nike Air Max 90 Futura",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 150,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/f4b7d3bf-12ab-45d1-9748-08c628fa6f8b/air-max-90-futura-womens-shoes-kvRZ4h.png",
    },
    "Nike Air Vapor Max 2023": {
      id: 3,
      name: "Nike Air Vapor Max 2023",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/833bdbe5-7a00-436e-9e8a-d20006bf24ed/air-vapormax-2023-flyknit-womens-shoes-HtMgGW.png",
    },
    "Nike Air Max Premium": {
      id: 4,
      name: "Nike Air Max Premium",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/bf6f67cc-bc9c-4ff0-993e-ec6c5368dbbe/air-max-1-86-premium-shoes-pqMlR0.png",
    },
    "Nike Air Max Isla": {
      id: 5,
      name: "Nike Air Max Isla",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4a884d25-ce26-4078-8a7d-5f06a59ef165/air-max-isla-womens-sandals-TSzfGq.png",
    },
    "Nike Air Max Serena": {
      id: 6,
      name: "Nike Air Max Serena",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b3512cdd-d117-45a1-838e-9e3bafa68821/air-max-1-x-serena-williams-design-crew-womens-shoes-dWGlVf.png",
    },
    "Nike Air Max Ishod": {
      id: 7,
      name: "Nike Air Max Ishod",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/3e2b5818-9b39-4511-9e50-efbc51ca97cc/air-max-ishod-mens-shoes-DwRtpQ.png",
    },
    "Nike Air Max Dawn": {
      id: 8,
      name: "Nike Air Max Dawn",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1179fcfd-66fb-47fd-abd6-f2291c7599b9/air-max-dawn-womens-shoes-224mWf.png",
    },
    "Nike Air Vapormax Plus": {
      id: 9,
      name: "Nike Air Vapormax Plus",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/aebf7012-706b-4106-9813-8479e169b65c/air-vapormax-plus-womens-shoes-xbt7zf.png",
    },
    "Nike Air Max P27": {
      id: 10,
      name: "Nike Air Max P27",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/aff58eab-0dbe-4330-a443-0c2e4f9ce5a1/air-max-1-87-premium-womens-shoes-FWHTjq.png",
    },
    "Nike Air Max Axis": {
      id: 11,
      name: "Nike Air Max Axis",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/5458a9ae-1108-4e41-b051-903b60ba06d7/air-max-axis-womens-shoes-cCWT9q.png",
    },
    "Nike Air Max Williams": {
      id: 12,
      name: "Nike Air Max Williams",
      brand: "NIKE",
      gender: "WOMEN",
      category: "OUTDOOR",
      price: 120,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9f3a9fe8-2620-4d09-9981-45916772ee82/air-max-1-x-serena-williams-design-crew-shoes-rXLHBc.png",
    },
  },
  kids: {
    "Nike Force Low": {
      id: 1,
      name: "Nike Force Low",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/804e41b0-fddb-4f59-a5dc-d60dd0a90858/force-1-low-easyon-little-kids-shoes-hrvqN1.png",
      slug: "",
      featured: 0,
    },
    "Nike Air Max EasyOn": {
      id: 2,
      name: "Nike Air Max EasyOn",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/dce1a7fc-14f1-44bf-a65b-c3895f40738d/air-max-1-easyon-little-kids-shoes-mx0nl8.png",
      slug: "",
      featured: 0,
    },
    "Nike Air Max 270": {
      id: 3,
      name: "Nike Air Max 270",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9be1cd76-d086-43e6-a791-b79fe6ab520e/air-max-270-little-kids-shoe-RStNgd.png",
      slug: "",
      featured: 0,
    },
    "Nike Blazer Mid 77": {
      id: 4,
      name: "Nike Blazer Mid 77",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/1f64924b-0da5-49fd-857a-533684e27b96/blazer-mid-77-little-kids-shoes-Bnnf4k.png",
      slug: "",
      featured: 0,
    },
    "Nike Air Max SE EasyOn": {
      id: 5,
      name: "Nike Air Max SE EasyOn",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/17e5d981-51fe-4f4e-94cd-830db2cc708d/air-max-1-se-easyon-little-kids-shoes-g41t00.png",
      slug: "",
      featured: 0,
    },
    "Nike Dunk Low": {
      id: 6,
      name: "Nike Dunk Low",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a6ca016f-5fa9-4a5f-8354-b05c93f96f7a/dunk-low-little-kids-shoes-NVTDbR.png",
      slug: "",
      featured: 0,
    },
    "Nike Court Legacy": {
      id: 7,
      name: "Nike Court Legacy",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/633f74f9-843b-4325-9ed6-e413018c6cbc/court-legacy-little-kids-shoes-Mb7npn.png",
      slug: "",
      featured: 0,
    },
    "Nike Dunk Lows": {
      id: 8,
      name: "Nike Dunk Lows",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/9b607f8d-a48a-46ab-9e22-9bc73e9fffa5/dunk-low-little-kids-shoes-L7bXXz.png",
      slug: "",
      featured: 0,
    },
    "Nike Flex Runner 3": {
      id: 9,
      name: "Nike Flex Runner 3",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL:
        "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/3c15f403-05be-4a9e-a893-617376a53b9f/flex-runner-3-little-kids-shoes-703XJt.png",
      slug: "",
      featured: 0,
    },
    "Nike GT Cut SE": {
      id: 10,
      name: "Nike GT Cut SE",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/fbbd14ca-fea9-4d88-8799-022332e8dd67/gt-cut-3-se-little-kids-basketball-shoes-WCV5Dn.png",
      slug: "",
      featured: 0,
    },
    "Nike Star Runner 4": {
      id: 11,
      name: "Nike Star Runner 4",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/372ea4c8-8990-479d-a3ce-4eb72e48aae6/star-runner-4-little-kids-shoes-D8kzVQ.png",
      slug: "",
      featured: 0,
    },
    "Nike Court Borough Mid": {
      id: 12,
      name: "Nike Court Borough Mid",
      brand: "NIKE",
      gender: "KIDS",
      category: "CASUAL",
      price: 90,
      is_in_inventory: true,
      items_left: 3,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/8fe801b3-2ccd-4672-bc1d-4d503438dc29/court-borough-mid-2-little-kids-shoes-c6LRCk.png",
      slug: "",
      featured: 0,
    },
  },
  customize: {},
};

export default products;
